volumes:
  artifactory-cpp-ce-data:
  artifactory-cpp-ce-database-data:

networks:
  artifactory-cpp-ce-network:
    name: artifactory-cpp-ce-network

services:
  artifactory:
    depends_on:
      - database
    build:
      context: .
      args:
        VERSION: ${ARTIFACTORY_VERSION}
    container_name: artifactory-cpp-ce
    environment:
      JF_ROUTER_ENTRYPOINTS_EXTERNALPORT: ${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}
    volumes:
      - artifactory-cpp-ce-data:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    networks:
      - artifactory-cpp-ce-network
    ports:
      - "8082:${JF_ROUTER_ENTRYPOINTS_EXTERNALPORT}"
      - "8081:8081"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  database:
    image: releases-docker.jfrog.io/postgres:13.10-alpine
    container_name: artifactory-cpp-ce-database
    environment:
      POSTGRES_DB: "artifactory"
      POSTGRES_USER: "artifactory"
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - artifactory-cpp-ce-database-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - artifactory-cpp-ce-network
    ports:
      - "54321:5432"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
